### ISSUE TITLE
Wrong Date on METARs...

### ISSUE THREAD

**Issue by ludwig27** [markyharris/metar#1]
Just installed latest image (11-25-2023), and all is working well with RPi Zero, but METARs are dated from 4 days ago... cant seem to be able to change this anywhere. RPi date and time are correct.
Any idea of what might be going on?

**Comment by ludwig27** [comment]
Looks like this is a problem with the API itself. Requests made from a browser using "https://api.weather.gov/stations/"+airport+"/observations/latest" already gives a METAR that is 4 days old...
Will test again in the New Year, perhaps related with date change... ??

**Comment by markyharris** [comment]
You are correct. I'm currently re-writing the code to use the new FAA API at https://aviationweather.gov/data/api/.
I'm hoping to have it all fixed in the next few days. It's a pretty big undertaking but its coming along. More to come. - Mark

**Comment by ludwig27** [comment]
Thanks for the update Mark , and Happy New Year!
Luis

**Comment by markyharris** [comment]
I just uploaded the latest version to Github. I'm still in the testing
phase, but feel free to update and let me know how it works for you.
Mark

**Comment by ludwig27** [comment]
Thanks Mark.  Updated via SSH.
Simple test from SSH command line is generating error now:

pi@METARs:~/metar $ sudo python3 metar_main.py KIAH 2 60 1
Traceback (most recent call last):
  File "/home/pi/metar/metar_main.py", line 88, in <module>
    use_remarks = int(sys.argv[5])
IndexError: list index out of range

Perhaps arguments have now changed? - Porbably not, since the following is also giving an error:

pi@METARs:~/metar $ sudo python3 metar_main.py
Traceback (most recent call last):
  File "/home/pi/metar/metar_main.py", line 84, in <module>
    metar = str(sys.argv[1])
IndexError: list index out of range

**Comment by markyharris** [comment]
Yep, its a work in process. I've made more headway today and will be
updating Github later tonight.
More to come.
Mark

**Comment by markyharris** [comment]
I just uploaded updated code that seems to be working. Please let me know
what issues you see.
Thanks for your feedback.
Mark

**Comment by ludwig27** [comment]
Appears to be working well. Seemed to have some issue with one of the displays (not sure which one), as random display would suddenly not update any more at some points.

**Comment by markyharris** [comment]
Good news. I'm still working on it and cleaning up little issues. If you
see anything in particular please let me know. Still a work in progress.
Thanks
Mark
