### ISSUE TITLE
Module Error on run of metar_main.py

### ISSUE THREAD

**Issue by justaplane** [markyharris/metar#2]
RPI 4, Model B

sudo python3 metar_main.py
Traceback (most recent call last):
  File "/home/xxxxxxx/metar/metar_main.py", line 68, in <module>
    from waveshare_epd import epd7in5b_V2
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxxxx/metar/waveshare_epd/epd7in5b_V2.py", line 32, in <module>
    from . import epdconfig
  File "/home/xxxxxxx/metar/waveshare_epd/epdconfig.py", line 154, in <module>
    implementation = JetsonNano()
                     ^^^^^^^^^^^^
  File "/home/xxxxxxx/metar/waveshare_epd/epdconfig.py", line 115, in __init__
    import Jetson.GPIO
ModuleNotFoundError: No module named 'Jetson'

**Comment by Flatiner** [comment]
> RPI 4, Model B
> 
> sudo python3 metar_main.py Traceback (most recent call last): File "/home/xxxxxxx/metar/metar_main.py", line 68, in from waveshare_epd import epd7in5b_V2 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xxxxxxx/metar/waveshare_epd/epd7in5b_V2.py", line 32, in from . import epdconfig File "/home/xxxxxxx/metar/waveshare_epd/epdconfig.py", line 154, in implementation = JetsonNano() ^^^^^^^^^^^^ File "/home/xxxxxxx/metar/waveshare_epd/epdconfig.py", line 115, in **init** import Jetson.GPIO ModuleNotFoundError: No module named 'Jetson'

Use the image the owner made. Works for me.
